/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/pf.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AC.geometry}
        material={nodes.AC.material}
        position={[-1.259, 2.748, -2.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa_body.geometry}
        material={nodes.sofa_body.material}
        position={[1.37, 1.111, 1.842]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa_bottom.geometry}
        material={nodes.sofa_bottom.material}
        position={[1.37, 1.111, 1.878]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa_cushion_02.geometry}
        material={nodes.sofa_cushion_02.material}
        position={[1.658, 0.76, 1.557]}
        rotation={[0, 0, 0.815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa_cushion_01.geometry}
        material={nodes.sofa_cushion_01.material}
        position={[1.37, 0.868, 2.231]}
        rotation={[-1.229, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        material={nodes.floor.material}
        position={[-2.394, 0.087, -1.427]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.room_bottom.geometry}
        material={nodes.room_bottom.material}
        position={[0, -0.022, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.room_right.geometry}
        material={nodes.room_right.material}
        position={[0, -0.022, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.room_left.geometry}
        material={nodes.room_left.material}
        position={[0, -0.022, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.photo.geometry}
        material={nodes.photo.material}
        position={[-2.534, 2.223, -1.267]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trash.geometry}
        material={nodes.trash.material}
        position={[-2.294, 0.328, 0.319]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain_bar.geometry}
        material={nodes.curtain_bar.material}
        position={[1.341, 2.701, -2.409]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain_right.geometry}
        material={nodes.curtain_right.material}
        position={[2.195, 1.773, -2.402]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain_left.geometry}
        material={nodes.curtain_left.material}
        position={[0.507, 1.773, -2.402]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ring_right.geometry}
        material={nodes.ring_right.material}
        position={[2.536, 2.701, -2.409]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ring_left.geometry}
        material={nodes.ring_left.material}
        position={[0.185, 2.701, -2.409]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.holder_left.geometry}
        material={nodes.holder_left.material}
        position={[0.183, 2.715, -2.466]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.holder_right.geometry}
        material={nodes.holder_right.material}
        position={[2.536, 2.715, -2.466]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_border.geometry}
        material={nodes.window_border.material}
        position={[0, -0.022, 0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_body.geometry}
        material={nodes.guitar_body.material}
        position={[-1.123, 0.525, 0.22]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_neck.geometry}
        material={nodes.guitar_neck.material}
        position={[-1.207, 1.02, 0.079]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_hold.geometry}
        material={nodes.guitar_hold.material}
        position={[-1.207, 1.02, 0.079]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_06.geometry}
        material={nodes.string_06.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_h.geometry}
        material={nodes.guitar_h.material}
        position={[-1.099, 0.431, 0.261]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_hold.geometry}
        material={nodes.string_hold.material}
        position={[-1.321, 1.601, -0.111]}
        rotation={[1.274, 0.173, -2.071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_head.geometry}
        material={nodes.guitar_head.material}
        position={[-1.324, 1.649, -0.116]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guitar_t.geometry}
        material={nodes.guitar_t.material}
        position={[-1.161, 0.75, 0.158]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_01.geometry}
        material={nodes.string_01.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_02.geometry}
        material={nodes.string_02.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_03.geometry}
        material={nodes.string_03.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_04.geometry}
        material={nodes.string_04.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.string_05.geometry}
        material={nodes.string_05.material}
        position={[-1.237, 1.021, 0.098]}
        rotation={[1.274, 0.173, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_legs.geometry}
        material={nodes.table_legs.material}
        position={[-1.713, 0.197, -0.254]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_stand.geometry}
        material={nodes.table_stand.material}
        position={[-1.713, 1.087, -0.254]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_stand_side.geometry}
        material={nodes.table_stand_side.material}
        position={[-1.712, 0.335, -0.311]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_body.geometry}
        material={nodes.table_body.material}
        position={[-1.717, 1.111, -1.177]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table_holder.geometry}
        material={nodes.table_holder.material}
        position={[-1.713, 1.087, -0.254]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mousepad.geometry}
        material={nodes.mousepad.material}
        position={[-1.298, 1.228, -1.924]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cup.geometry}
        material={nodes.cup.material}
        position={[-1.374, 1.309, -0.432]}
        rotation={[-Math.PI, 1.538, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tk_book.geometry}
        material={nodes.tk_book.material}
        position={[-1.988, 1.262, -0.275]}
        rotation={[Math.PI / 2, 0, 0.722]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box.geometry}
        material={nodes.box.material}
        position={[-1.99, 1.442, -1.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.deck02.geometry}
        material={nodes.deck02.material}
        position={[-2.063, 1.322, -0.614]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.deck01.geometry}
        material={nodes.deck01.material}
        position={[-2.22, 1.241, -0.614]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.scroll_wheel.geometry}
        material={nodes.scroll_wheel.material}
        position={[-1.391, 1.273, -1.991]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mouse_body.geometry}
        material={nodes.mouse_body.material}
        position={[-1.327, 1.264, -1.991]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mb_01.geometry}
        material={nodes.mb_01.material}
        position={[-1.327, 1.264, -1.991]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mb_02.geometry}
        material={nodes.mb_02.material}
        position={[-1.327, 1.264, -1.991]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keyboard_case.geometry}
        material={nodes.keyboard_case.material}
        position={[-1.284, 1.262, -1.225]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keycaps.geometry}
        material={nodes.keycaps.material}
        position={[-1.199, 1.283, -1.325]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-1.422, 1.26, -1.035]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop_keyboard.geometry}
        material={nodes.laptop_keyboard.material}
        position={[-2.148, 1.472, -1.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop_body.geometry}
        material={nodes.laptop_body.material}
        position={[-1.976, 1.442, -1.239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop_head.geometry}
        material={nodes.laptop_head.material}
        position={[-2.349, 1.688, -1.239]}
        rotation={[0, 0, -1.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.port_lap_key.geometry}
        material={nodes.port_lap_key.material}
        position={[-2.092, 1.466, -0.883]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.port_lap_mouse.geometry}
        material={nodes.port_lap_mouse.material}
        position={[-2.044, 1.466, -0.883]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.port_lap_hdd.geometry}
        material={nodes.port_lap_hdd.material}
        position={[-1.891, 1.466, -1.596]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.port_hdd_lap.geometry}
        material={nodes.port_hdd_lap.material}
        position={[-2.016, 1.458, -1.712]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop_screen.geometry}
        material={nodes.laptop_screen.material}
        position={[-2.349, 1.688, -1.239]}
        rotation={[0, 0, -1.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cable_lap_key.geometry}
        material={nodes.cable_lap_key.material}
        position={[-1.119, 1.442, -0.254]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hdd.geometry}
        material={nodes.hdd.material}
        position={[-2.15, 1.456, -1.713]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cable_lap_hdd.geometry}
        material={nodes.cable_lap_hdd.material}
        position={[-1.432, 1.486, -1.667]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spray_body.geometry}
        material={nodes.spray_body.material}
        position={[2.419, 0.377, -2.131]}
        rotation={[0, 0.649, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spray_top.geometry}
        material={nodes.spray_top.material}
        position={[2.419, 0.731, -2.131]}
        rotation={[0, 0.649, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_side.geometry}
        material={nodes.af_side.material}
        position={[1.399, 0.359, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_bar_h.geometry}
        material={nodes.af_bar_h.material}
        position={[1.819, 0.161, -2.014]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_bar_v.geometry}
        material={nodes.af_bar_v.material}
        position={[1.5, 0.356, -2.007]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_metal.geometry}
        material={nodes.af_metal.material}
        position={[1.431, 0.26, -2.109]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_lamp.geometry}
        material={nodes.af_lamp.material}
        position={[1.628, 0.26, -2.109]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_bot.geometry}
        material={nodes.af_bot.material}
        position={[1.819, 0.114, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.af_top.geometry}
        material={nodes.af_top.material}
        position={[1.819, 0.704, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_top.geometry}
        material={nodes.chair_top.material}
        position={[-0.282, 1.301, -1.265]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_bot.geometry}
        material={nodes.chair_bot.material}
        position={[-0.564, 0.835, -1.157]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_side.geometry}
        material={nodes.chair_side.material}
        position={[-0.34, 0.964, -0.692]}
        rotation={[Math.PI / 2, 0, -0.327]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_bot_plastic.geometry}
        material={nodes.chair_bot_plastic.material}
        position={[-0.566, 0.708, -1.157]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_side_holder.geometry}
        material={nodes.chair_side_holder.material}
        position={[-0.503, 0.734, -1.178]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_knee.geometry}
        material={nodes.chair_knee.material}
        position={[-0.566, 0.505, -1.157]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_leg_holder.geometry}
        material={nodes.chair_leg_holder.material}
        position={[-0.566, 0.653, -1.157]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_skeleton.geometry}
        material={nodes.chair_skeleton.material}
        position={[-0.194, 1.186, -1.28]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_back.geometry}
        material={nodes.chair_back.material}
        position={[-0.165, 0.777, -1.294]}
        rotation={[0, 0.327, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_spine.geometry}
        material={nodes.chair_spine.material}
        position={[-0.103, 1.083, -1.311]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_set.geometry}
        material={nodes.chair_set.material}
        position={[-0.351, 0.539, -1.23]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_pipe.geometry}
        material={nodes.chair_pipe.material}
        position={[-0.351, 0.632, -1.23]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_leg.geometry}
        material={nodes.chair_leg.material}
        position={[-0.566, 0.218, -1.157]}
        rotation={[0, 0.327, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_wheel.geometry}
        material={nodes.chair_wheel.material}
        position={[-0.991, 0.148, -0.839]}
        rotation={[-Math.PI, 0.93, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_wheel_stand.geometry}
        material={nodes.chair_wheel_stand.material}
        position={[-0.405, 0.18, -0.683]}
        rotation={[Math.PI, -0.327, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/pf.glb");
